<a href="https://colab.research.google.com/github/llcver7/Pro/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
file_path = "/content/Student Depression Dataset.csv"


df = pd.read_csv(file_path, encoding='utf-8')


df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [13]:
missing_rows = df[df.isnull().any(axis=1)]
print("\n عرض الصفوف التي تحتوي على قيم مفقودة:")
print(missing_rows)

 عرض الصفوف التي تحتوي على قيم مفقودة:
          id  Gender   Age       City Profession  Academic Pressure  \
4458   22377  Female  32.0   Varanasi    Student                3.0
13596  68910    Male  29.0  Hyderabad    Student                2.0
19266  97610  Female  20.0    Kolkata    Student                1.0

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
4458             0.0  5.64                 1.0               0.0
13596            0.0  8.94                 3.0               0.0
19266            0.0  6.83                 1.0               0.0

          Sleep Duration Dietary Habits Degree  \
4458           5-6 hours        Healthy    BCA
13596  Less than 5 hours      Unhealthy   B.Ed
19266          5-6 hours        Healthy   MBBS

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
4458                                     No              12.0
13596                                    No              12.0
19266                                    No               9.0

       Financial Stress Family History of Mental Illness  Depression
4458                NaN                               No           1
13596               NaN                              Yes           0
19266               NaN                              Yes           0

In [15]:
df.fillna(df.select_dtypes(include=['number']).mean(), inplace=True)
for column in df.select_dtypes(include=['object']).columns:
    if df[column].isnull().sum() > 0:
        df[column].fillna(df[column].mode()[0], inplace=True)

In [16]:
missing_rows = df[df.isnull().any(axis=1)]
print("\n After cleaning")
print(missing_rows)

🔹 عرض الصفوف التي تحتوي على قيم مفقودة:
Empty DataFrame
Columns: [id, Gender, Age, City, Profession, Academic Pressure, Work Pressure, CGPA, Study Satisfaction, Job Satisfaction, Sleep Duration, Dietary Habits, Degree, Have you ever had suicidal thoughts ?, Work/Study Hours, Financial Stress, Family History of Mental Illness, Depression]
Index: []

In [18]:
import numpy as np
Q1 = df.select_dtypes(include=['number']).quantile(0.25)
Q3 = df.select_dtypes(include=['number']).quantile(0.75)
IQR = Q3 - Q1
outliers = ((df.select_dtypes(include=['number']) < (Q1 - 1.5 * IQR)) |
            (df.select_dtypes(include=['number']) > (Q3 + 1.5 * IQR)))
print("\n Number of outliers :")
print(outliers.sum())

 Number of outliers :
id                     0
Age                   12
Academic Pressure      0
Work Pressure          3
CGPA                   9
Study Satisfaction     0
Job Satisfaction       8
Work/Study Hours       0
Financial Stress       0
Depression             0
dtype: int64

In [21]:
df_cleaned = df[~((df.select_dtypes(include=['number']) < (Q1 - 1.5 * IQR)) |
                   (df.select_dtypes(include=['number']) > (Q3 + 1.5 * IQR))).any(axis=1)]

print(f"\nNumber of rows before cleaning: {df.shape[0]}")
print(f"Number of rows after cleaning: {df_cleaned.shape[0]}")

Number of rows before cleaning: 27901
Number of rows after cleaning: 27878